(define (problem BLOCKS-5-0) 
    (:domain BLOCKS)
    (:objects
        B E A C D 
    )
    (:init
        (clear E)
        (clear A)
        (clear B)
        (ontable E)
        (ontable A)
        (ontable B)
        (clear D)
        (ontable C)
        (on D C)
        (handempty)
    )
    (:goal (and
        (ontable A)
        (ontable D)
        (on E C)
        (on C A)
        (clear E)
        (ontable D)
        (on B D)
        (clear B)
        (handempty)  
    ))
)
